features:
  - O00391
  - P05067
  - O00391_UPDRS3_interact

params:
  objective: "regression"
  metric: "rmse"
  num_leaves: 31
  learning_rate: 0.05
  feature_fraction: 0.9
  bagging_fraction: 0.8
  bagging_freq: 5
  verbose: -1